import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Layout from '../components/Layout'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Hiro Portfolio</title>
        <meta name="description" content="Generated by Next.js" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Layout></Layout>

      <main>
        <div className="flex flex-col justify-center items-center h-screen">
          <div className=""><img src="/images/hiroPicture.jpg" className="w-40 h-40 rounded-full border transition-transform duration-75" /></div>
          <h1 className="font-thin text-4xl text-gray-500 my-8">HIRO KOBA</h1>
          <h2 className="font-thin text-3xl text-gray-500">A Web Developer</h2>
          <h2 className="font-thin text-3xl text-gray-500">London University Student</h2>
          <div className='flex mt-5'>
            <div className="mx-5"><img src="images/Twitter_logo.png" className="w-8" /></div>
            <div className="mx-5"><img src="images/Instagram_logo.png" className="w-8" /></div>
          </div>
        </div>
      </main>
    </>
  );
}
